version: '2'

volumes:
  climbon-postgres:
    external:
      name: climbon-postgres
  climbon-redis:
    external:
      name: climbon-redis
  climbon-elasticsearch:
    external:
      name: climbon-elasticsearch

services:
  postgres:
    image: postgres:9.4.5
    container_name: postgres
    network_mode: bridge
    ports:
      - "5432:5432"
    volumes:
      - climbon-postgres:/var/lib/postgresql/data

  # redis:
  #   image: redis:3.0.5
  #   container_name: redis
  #   network_mode: bridge
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - climbon-redis:/var/lib/redis/data

  # elasticsearch:
  #   image: elasticsearch:2.2.0
  #   container_name: elasticsearch
  #   network_mode: bridge
  #   ports:
  #     - "9200:9200"
  #     - "9300:9300"
  #   volumes:
  #     - climbon-elasticsearch:/var/lib/elasticsearch/data

  climbon-auth:
    build: climbon-auth
    image: climbon-auth:latest
    container_name: climbon-auth
    network_mode: bridge
    links:
      - postgres
    volumes:
      - ./climbon-auth:/app
    ports:
      - "8080:8080"
    env_file:
      - ./climbon-auth/.env
    tty: true
    stdin_open: true
